Do not strip excess leading dashes on long option names
pkgjs/parseargs pull request #21
Opened 2021-12-04 02:08 UTC by shadowspawn

## Problem

All leading dashes on options are being stripped. This was probably to allow `-foo` treated the same as `--foo` for some circumstances, but that approach is being reconsidered to fully support short option flags and have simple consistent behaviour.

Note: the preflight checks in current limited code mean this is only affecting two or more dashes. 

See #7 (and #1)

## Solution

Only strip the two leading dashes of an option with two or more leading dashes.

`---foo` is parsed as an option named `-foo`.

2021-12-04 15:57 UTC, bcoe approved these changes
@joesepi personally, I think this is a good resolution to #7, if you provide an extra dash you get the variable `-foo`, this is nice because the person using the library can then choose how they deal with this value.

2021-12-20 20:04 UTC, bcoe requested changes
I think the tests will need to be updated to `flags`.

2021-12-21 04:27 UTC, shadowspawn commented
Test updated.

2021-12-21 17:29 UTC, bcoe approved these changes

2021-12-21 17:29 UTC, merged